DROP TABLE IF EXISTS `warnarchiv`;
CREATE TABLE `warnarchiv` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`datum` datetime NOT NULL,
	`hash` varchar(32) NOT NULL,
	`identifier` varchar(1024) NOT NULL,
	`reference` varchar(1024) DEFAULT NULL,
	`msgType` varchar(32) NOT NULL,
	`event` varchar(255) NOT NULL,
	`startzeit` datetime NOT NULL,
	`endzeit` datetime NOT NULL,
	`severity` varchar(255) NOT NULL,
	`warnstufe` int(11) NOT NULL,
	`urgency` varchar(255) NOT NULL,
	`headline` varchar(1024) NOT NULL,
	`description` text NOT NULL,
	`instruction` text NOT NULL,
	`sender` varchar(255) NOT NULL,
	`web` varchar(255) NOT NULL,
	`warncellid` int(10) unsigned NOT NULL,
	`area` varchar(255) NOT NULL,
	`stateLong` varchar(255) NOT NULL,
	`stateShort` varchar(3) NOT NULL,
	`altitude` int(10) unsigned NOT NULL,
	`ceiling` int(10) unsigned NOT NULL,
	`hoehenangabe` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `hash` (`hash`),
	KEY `datum` (`datum`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
